#########################################################################
# Title:            Sandbox: BookStack                                  #
# Author(s):        Thomvh, kowalski                                    #
# URL:              https://github.com/saltyorg/Sandbox                 #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Add DNS record
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/dns/tasker.yml"
  vars:
    dns_record: "{{ lookup('vars', role_name + '_dns_record') }}"
    dns_zone: "{{ lookup('vars', role_name + '_dns_zone') }}"
    dns_proxy: "{{ lookup('vars', role_name + '_dns_proxy') }}"

- name: MariaDB Role
  ansible.builtin.include_role:
    name: mariadb
  vars:
    mariadb_name: "{{ bookstack_name }}_mariadb"  # Remove when instance support merged into Saltbox
    mariadb_instances: ["{{ bookstack_name }}_mariadb"]
    mariadb_docker_env_db: "{{ bookstack_name }}"
    mariadb_paths_folder: "{{ bookstack_name }}"
    mariadb_paths_location: "{{ server_appdata_path }}/{{ mariadb_paths_folder }}/mariadb"

- name: MariaDB | Create bookstackapp database
  community.mysql.mysql_db:
    name: "{{ bookstack_name }}"
    login_host: "{{ bookstack_name }}_mariadb"
    login_user: "{{ mariadb_docker_env_user }}"
    login_password: "{{ mariadb_docker_env_password }}"
    state: present

- name: Import Default MariaDB variables
  ansible.builtin.include_vars: /srv/git/saltbox/roles/mariadb/defaults/main.yml

- name: Remove existing Docker container
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/docker/remove_docker_container.yml"

- name: Create directories
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/directories/create_directories.yml"

- name: Create Docker container
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/docker/create_docker_container.yml"
